version: '2'
services:
  customerfeedback-app:
    image: customerfeedback
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customerfeedback-postgresql:5432/customerFeedBack
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8089:8089
  customerfeedback-postgresql:
    extends:
      file: postgresql.yml
      service: customerfeedback-postgresql
